#!/usr/bin/env bash

# Install native apps
brew tap phinze/homebrew-cask
brew install brew-cask

function installcask() {
	brew cask install "${@}" 2> /dev/null
}

installcask google-chrome
installcask google-chrome-canary
installcask iterm2
installcask macvim
installcask vlc
